export const USER = {
  GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
  CLEAR_ACCESS_TOKEN: 'CLEAR_ACCESS_TOKEN',
  GET_USER_INFO: 'GET_USER_INFO',
  CLEAR_USER_INFO: 'CLEAR_USER_INFO',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
}