export const SERVICES = {
  SET_SERVICES: 'SET_SERVICES',
  SET_SERVICE_CHECK: 'SET_SERVICE_CHECK',
  SET_ONE_SERVICE_CHECK: 'SET_ONE_SERVICE_CHECK',
  UNCHECK_ALL_SERVICES: 'UNCHECK_ALL_SERVICES',
  ADD_CUSTOM_SERVICE: 'ADD_CUSTOM_SERVICE',
  CLEAR_CUSTOM_SERVICES: 'CLEAR_CUSTOM_SERVICES'
}